export type {
  ArticlePageData,
  ArticlePageSection,
  ContentArticleSection,
  ContentSection,
  SectionContent,
  SectionLink as ContentLink,
  ListEntry,
  RelatedLink,
  FeatureGridItem,
  ProofItem,
  ProcessItem,
  SliderSectionItem,
  FaqItem,
} from "@/types/sections";
